version: '3'

services:

  database:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017' 

  mongo-seed:
    container_name: seed
    build: .
    command: 'npm run seedmongo'
    depends_on:
      - 'database'

  server:
    container_name: server
    build: .
    depends_on:
      - 'database'
    ports:
      - '3001:3001'
    command: 'npm run server-dev'

  # topplayer:
  #   container_name: topplayer
  #   build: .
  #   depends_on:
  #     - 'server'